language: node_js
node_js:
  - '8'
  - '10'
  - lts/*
  - node
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - test ! -d node_modules || npm prune
scripts:
  - npm run test
  - npm run build
after_script:
  - test $TRAVIS_NODE_VERSION != '10' && sonar-scanner
notifications:
  email:
    recipients:
    - dragos.cirjan+glasswingjs@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "glasswingjs"
    token:
      secure: "f+vzTkN0y5wVcAGh/D34GJQKMdX7KHQgUPUjJsv9GFOOyVrX+Kv934bPjgN71lkGyuKbAYguPM8wy4KrpfzyFf+jqKm7K1BFzTk/WIL/wlhyY/NNMzQkoztY4k0gcavsBB9EDPRMSrk4yVD7n1JNjq17SWPOZROu9RENR2T1eX/OD78aUhyzhja3F/uxpe4lgSKh5nMZPt3vEcvGccwWo5Q+WOaXUb2Xo8KhaDwAXDWHU6IjY/b8/vidYm2DA/HGX+rnj95F+0ZfPnVdCn6snDZlwKmv/0TW0gCNTgLKR7qOaTNq/O+BPmL6UdJYZQQf45kg4GfFAriaH2Pz1Hb7vfcHZ+HNxl7YbOZsSL1miPOakxGe9cqzz8p6Q+c2Ua5s/tP8fOJGlIh9uBupqf8E1RxrJNYjAyOufJQss/xQKVGoVRMwVVK16PGNUxj/E7TxM3n9xZumaNIsh7WOtyP+drPKpupmj4jWhqe6tSfhtRDRlYztLsI4v/KDF8UVxgFLUuqFI0nVdqk2qjpRJubnu8PvHB6ZW6DbZmMywiCY7VxjxDeWj5w8wbe4cWAVkVfIM07b8p3u77+iN2uAFglzHV8F6UZ+UdFpfnDVC4L6ifBApIBPb9zHv3y2MDhhMitDg9oul9mQ8EdsFgNbjakMtds/8v3mIV0w/G6ndYCxWHs="

